name: traffic2badge
on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 0 * * *' # Runs daily at 00:01 UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  run:
    name: Make GitHub Traffic to Badge
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating/updating the traffic branch
      actions: read    # Required for reading action outputs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TRAFFIC_TOKEN }}  # Use TRAFFIC_TOKEN for checkout as well
          fetch-depth: 0  # Fetch all history for all branches

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Get Commit Message
        id: message
        uses: actions/github-script@v7
        env:
          FULL_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
        with:
          result-encoding: string
          script: |
            var message = `${process.env.FULL_COMMIT_MESSAGE}`;
            core.info(message);
            if (message != '') return message;
            var time = new Date(Date.now()).toISOString();
            core.info(time);
            return `Update traffic data at ${time}`;

      - name: Set Traffic
        id: traffic
        uses: yi-Xu-0100/traffic-to-badge@v1.4.0
        with:
          my_token: ${{ secrets.TRAFFIC_TOKEN }}
          static_list: ${{ github.repository }}
          traffic_branch: traffic
          views_color: brightgreen
          clones_color: brightgreen
          views_week_color: brightgreen
          clones_week_color: brightgreen
          total_views_color: brightgreen
          total_clones_color: brightgreen
          total_views_week_color: brightgreen
          total_clones_week_color: brightgreen
          logo: github

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          personal_token: ${{ secrets.TRAFFIC_TOKEN }}  # Use TRAFFIC_TOKEN which has write permissions
          publish_branch: ${{ steps.traffic.outputs.traffic_branch }}
          publish_dir: ${{ steps.traffic.outputs.traffic_path }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: ${{ steps.message.outputs.result }}
          keep_files: false
          force_orphan: true # This helps with first-time branch creation

      - name: Show Traffic Data
        run: |
          echo "Traffic branch: ${{ steps.traffic.outputs.traffic_branch }}"
          echo "Traffic path: ${{ steps.traffic.outputs.traffic_path }}"
          cd ${{ steps.traffic.outputs.traffic_path }}
          ls -a